import fs from 'node:fs';
import path from 'node:path';
import { formatNotebookRef, formatRanges, loadEntries, pageCoverage } from './entries.js';

const cell = (value) => String(value ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim() || '—';

function link(entry) {
  return `[${cell(entry.title)}](${entry.file}#${entry.anchor})`;
}

function groupBy(entries, keyFn) {
  const map = new Map();
  for (const entry of entries) {
    for (const key of [].concat(keyFn(entry))) {
      if (key == null || key === '') continue;
      if (!map.has(key)) map.set(key, []);
      map.get(key).push(entry);
    }
  }
  return map;
}

function sortedKeys(map) {
  return [...map.keys()].sort((a, b) => String(a).localeCompare(String(b), undefined, { numeric: true }));
}

function notebookSection(entries) {
  const byNotebook = groupBy(entries, (e) => (e.notebook ? e.notebook.id : null));
  const out = ['## Physical notebooks', ''];
  if (!byNotebook.size) {
    out.push('_No entries carry a **Notebook:** reference yet._', '');
    return out;
  }
  for (const id of sortedKeys(byNotebook)) {
    const rows = byNotebook.get(id).slice().sort((a, b) => {
      const aStart = a.notebook.start ?? Number.MAX_SAFE_INTEGER;
      const bStart = b.notebook.start ?? Number.MAX_SAFE_INTEGER;
      return aStart - bStart || String(a.date).localeCompare(String(b.date));
    });
    const { covered, gaps, pages } = pageCoverage(rows);
    out.push(`### ${id}`, '');
    out.push(`- **Entries:** ${rows.length}`);
    out.push(`- **Pages logged:** ${formatRanges(covered)}${pages.length ? ` (${pages.length} page${pages.length === 1 ? '' : 's'})` : ''}`);
    out.push(`- **Gaps:** ${formatRanges(gaps)}`);
    out.push('');
    out.push('| Page | Date | Entry | Machine | Status | Tags |');
    out.push('| --- | --- | --- | --- | --- | --- |');
    for (const entry of rows) {
      const ref = entry.notebook;
      const page = ref.start == null ? '—' : ref.start === ref.end ? `${ref.start}` : `${ref.start}-${ref.end}`;
      out.push(`| ${page} | ${cell(entry.date)} | ${link(entry)} | ${cell(entry.machine)} | ${cell(entry.status)} | ${cell(entry.tags.map((t) => `#${t}`).join(' '))} |`);
    }
    out.push('');
  }
  return out;
}

function listSection(title, map, emptyNote) {
  const out = [`## ${title}`, ''];
  if (!map.size) {
    out.push(emptyNote, '');
    return out;
  }
  for (const key of sortedKeys(map)) {
    const rows = map.get(key);
    out.push(`### ${key} (${rows.length})`, '');
    for (const entry of rows) {
      const ref = entry.notebook ? ` — ${formatNotebookRef(entry.notebook)}` : '';
      out.push(`- ${cell(entry.date)} · ${link(entry)}${ref}`);
    }
    out.push('');
  }
  return out;
}

function chronologicalSection(entries) {
  const out = ['## Chronological', ''];
  if (!entries.length) {
    out.push('_Nothing logged yet._', '');
    return out;
  }
  const byDate = groupBy(entries, (e) => e.date || 'undated');
  const dates = sortedKeys(byDate).reverse();
  // Dated entries first, newest to oldest; anything undated trails at the end.
  dates.sort((a, b) => Number(a === 'undated') - Number(b === 'undated'));
  for (const date of dates) {
    out.push(`### ${date}`, '');
    for (const entry of byDate.get(date)) {
      const bits = [entry.time, link(entry)];
      if (entry.notebook) bits.push(formatNotebookRef(entry.notebook));
      if (entry.machine) bits.push(entry.machine);
      out.push(`- ${bits.filter(Boolean).map((b) => cell(b)).join(' · ')}`);
    }
    out.push('');
  }
  return out;
}

export function renderIndex(entries, { generatedAt = new Date() } = {}) {
  const withNotebook = entries.filter((e) => e.notebook);
  const machines = groupBy(entries, (e) => e.machine);
  const tags = groupBy(entries, (e) => e.tags.map((t) => `#${t}`));
  const open = entries.filter((e) => String(e.status || '').toLowerCase() === 'open');

  const lines = [
    '# Vault Index',
    '',
    '<!-- Generated by `npm run index`. Do not edit by hand. -->',
    '',
    `- **Generated:** ${generatedAt.toISOString().replace('T', ' ').slice(0, 16)} UTC`,
    `- **Entries:** ${entries.length} (${withNotebook.length} tied to a physical notebook page)`,
    `- **Notebooks:** ${new Set(withNotebook.map((e) => e.notebook.id)).size}`,
    `- **Machines:** ${machines.size}`,
    `- **Tags:** ${tags.size}`,
    '',
  ];

  if (open.length) {
    lines.push('## Open items', '');
    for (const entry of open) {
      const ref = entry.notebook ? ` — ${formatNotebookRef(entry.notebook)}` : '';
      lines.push(`- ${cell(entry.date)} · ${link(entry)}${ref}${entry.machine ? ` · ${cell(entry.machine)}` : ''}`);
    }
    lines.push('');
  }

  lines.push(...notebookSection(entries));
  lines.push(...listSection('By machine', machines, '_No entries carry a **Machine:** line yet._'));
  lines.push(...listSection('By tag', tags, '_No tags yet._'));
  lines.push(...chronologicalSection(entries));

  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}

export function buildIndex(vaultDir, { write = true, generatedAt = new Date() } = {}) {
  const entries = loadEntries(vaultDir);
  const markdown = renderIndex(entries, { generatedAt });
  const json = {
    generatedAt: generatedAt.toISOString(),
    count: entries.length,
    entries: entries.map((entry) => ({
      file: entry.file,
      line: entry.line,
      section: entry.section,
      date: entry.date,
      time: entry.time,
      title: entry.title,
      anchor: entry.anchor,
      notebook: entry.notebook ? { id: entry.notebook.id, start: entry.notebook.start, end: entry.notebook.end } : null,
      machine: entry.machine,
      status: entry.status,
      tags: entry.tags,
      excerpt: entry.body.split('\n').filter(Boolean).slice(0, 2).join(' ').slice(0, 240),
    })),
  };
  if (write) {
    fs.writeFileSync(path.join(vaultDir, 'INDEX.md'), markdown);
    fs.writeFileSync(path.join(vaultDir, 'index.json'), `${JSON.stringify(json, null, 2)}\n`);
  }
  return { entries, markdown, json };
}
